# Generated by Django 3.2.16 on 2022-11-23 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='follow',
            name='external_follower',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='external_follower',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='external_post',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='external_comment',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='external_post',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='external_user',
            field=models.URLField(blank=True, null=True),
        ),
    ]
