# Generated by Django 3.2.16 on 2022-11-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221123_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='external_author',
            field=models.URLField(blank=True, null=True),
        ),
    ]
