# Generated by Django 3.2.16 on 2022-10-18 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20221017_2208"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="author",
            new_name="user",
        ),
    ]
