# Generated by Django 3.2.16 on 2022-11-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_external_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
    ]
