# Generated by Django 3.2.16 on 2022-10-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221018_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='github_url',
            new_name='github',
        ),
    ]
