# Generated by Django 3.2.16 on 2022-11-30 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inbox_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
