# Generated by Django 4.1.2 on 2022-10-22 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_github_url_user_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'text/plain'), ('MD', 'text/markdown'), ('APP64', 'application/base64'), ('PNG', 'image/png'), ('JPEG', 'image/jpeg')], default='TEXT', max_length=5),
        ),
    ]
