# Generated by Django 4.1.2 on 2022-10-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_author_alter_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.TextField(default='t'),
        ),
    ]
