# Generated by Django 4.1.2 on 2022-10-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.TextField(),
        ),
    ]
