# Generated by Django 4.1.2 on 2022-10-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(blank=True, choices=[('TEXT', 'text/plain'), ('MD', 'text/markdown'), ('APP64', 'application/base64'), ('PNG', 'image/png'), ('JPEG', 'image/jpeg')], default='TEXT', max_length=5),
        ),
    ]
