# Generated by Django 4.1.2 on 2022-10-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='private_to',
            field=models.TextField(blank=True),
        ),
    ]
