# Generated by Django 4.1.2 on 2022-11-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_post_private_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaultProPic.jpg', upload_to=''),
        ),
    ]
