# Generated by Django 3.2.16 on 2022-11-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
    ]
